### ISSUE TITLE
live demo 404 not found

### ISSUE THREAD

**Issue by jason-s** [danielcebrian/share-annotator#4]
> Live-Demo
> 
> There is a demo of the share annotation plugin in the next webpage:
> 
> http://danielcebrian.com/share-annotation/demo.html

but it just gives a 404 not found.

**Comment by danielcebrian** [comment]
you are right. Thank you for letting me know it. It is working now, but without backend. I will work on that later, sorry.

Best,
Daniel

**Comment by var-che** [comment]
Demo page works, but the plugin doesn't. Also, I downloaded this whole repository and opened "demo.html" and this is what it shows in the console. 

![jebaited](https://user-images.githubusercontent.com/480649/47776588-01ca5100-dcf3-11e8-9b85-a1d45ca717ac.png)

It doesn't work and gives all those errors.

**Comment by danielcebrian** [comment]
The annotator plugin used for this version is stopped as far as I saw it on its web: http://annotateit.org/.

I recommend you to try to install an old version of annotation or call to this group, because this plugin needs annotator 1.2.7.
